### ISSUE TITLE
Correct  Wal_size

### ISSUE THREAD

**Issue by abhishek-intel-smg** [intel/terraform-intel-azure-postgresql-flexible-server#20]
min_wal_size = optional(object({
        value = optional(string, "8192")
      }))
      max_wal_size = optional(object({
        value = optional(string, "524")

are these  the correct values ?  max size is less then min size ?

**Comment by lucasmelogithub** [comment]
@abhishek-intel-smg It it seems like we introduced a bug, that is not correct. It should be **'524288'**
I'm creating a PR right now, thank you for creating the issue, much appreciated!

**Comment by abhishek-intel-smg** [comment]
Hi @lucasmelogithub
in Azure Database for PostgreSQL flexible server , maximum Wal Size allowed in Azure is '65536'  not '534288' , Please check  

![image](https://github.com/intel/terraform-intel-azure-postgresql-flexible-server/assets/95842975/30f734e7-d3ca-4dab-be6c-756a10226a8b)

**Comment by lucasmelogithub** [comment]
Thanks again @abhishek-intel-smg , that's correct. 
Fixing now and will discuss with the team additional automation testing to help catch these in the future. 

Addressing at #22
